[default]
src = 'src'
out = 'out'
libs = ['lib']
remappings = ['ds-test/=lib/ds-test/src/', '@openzeppelin/=node_modules/@openzeppelin/']
optimizer = true
optimizer_runs = 200
fuzz_runs = 256
gas_reports = ["*"]
# See more config options https://github.com/gakonst/foundry/tree/master/config
sender='0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266'
bytecode_hash='none'
